# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mood_predictor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "mood_predictor.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14mood_predictor.proto\x12\rmoodpredictor"e\n\x0cSongFeatures\x12\x0f\n\x07song_id\x18\x01 \x01(\t\x12\r\n\x05tempo\x18\x02 \x01(\x01\x12\x0e\n\x06\x65nergy\x18\x03 \x01(\x01\x12\x0f\n\x07valence\x18\x04 \x01(\x01\x12\x14\n\x0c\x64\x61nceability\x18\x05 \x01(\x01"L\n\x16PredictUserMoodRequest\x12\x32\n\rsong_features\x18\x01 \x03(\x0b\x32\x1b.moodpredictor.SongFeatures".\n\x17PredictUserMoodResponse\x12\x13\n\x0bglobal_mood\x18\x01 \x01(\t2x\n\x14MoodPredictorService\x12`\n\x0fPredictUserMood\x12%.moodpredictor.PredictUserMoodRequest\x1a&.moodpredictor.PredictUserMoodResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "mood_predictor_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SONGFEATURES"]._serialized_start = 39
    _globals["_SONGFEATURES"]._serialized_end = 140
    _globals["_PREDICTUSERMOODREQUEST"]._serialized_start = 142
    _globals["_PREDICTUSERMOODREQUEST"]._serialized_end = 218
    _globals["_PREDICTUSERMOODRESPONSE"]._serialized_start = 220
    _globals["_PREDICTUSERMOODRESPONSE"]._serialized_end = 266
    _globals["_MOODPREDICTORSERVICE"]._serialized_start = 268
    _globals["_MOODPREDICTORSERVICE"]._serialized_end = 388
# @@protoc_insertion_point(module_scope)
