# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mood_predictor_pb2 as mood__predictor__pb2

GRPC_GENERATED_VERSION = "1.73.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in mood_predictor_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MoodPredictorServiceStub(object):
    """Definición del servicio gRPC"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictUserMood = channel.unary_unary(
            "/moodpredictor.MoodPredictorService/PredictUserMood",
            request_serializer=mood__predictor__pb2.PredictUserMoodRequest.SerializeToString,
            response_deserializer=mood__predictor__pb2.PredictUserMoodResponse.FromString,
            _registered_method=True,
        )


class MoodPredictorServiceServicer(object):
    """Definición del servicio gRPC"""

    def PredictUserMood(self, request, context):
        """Predice el estado de ánimo global de un usuario basado en sus canciones"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MoodPredictorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PredictUserMood": grpc.unary_unary_rpc_method_handler(
            servicer.PredictUserMood,
            request_deserializer=mood__predictor__pb2.PredictUserMoodRequest.FromString,
            response_serializer=mood__predictor__pb2.PredictUserMoodResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "moodpredictor.MoodPredictorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "moodpredictor.MoodPredictorService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MoodPredictorService(object):
    """Definición del servicio gRPC"""

    @staticmethod
    def PredictUserMood(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/moodpredictor.MoodPredictorService/PredictUserMood",
            mood__predictor__pb2.PredictUserMoodRequest.SerializeToString,
            mood__predictor__pb2.PredictUserMoodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
